name: Lint protobuf

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**/*.md"

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Run protolint
        uses: plexsystems/protolint-action@v0.4.0
        with:
          configDirectory: .protolint